### ISSUE TITLE
FateX 0.15 Actor Sheets nonfunctional

### ISSUE THREAD

**Issue by glennfrog191** [anvil-vtt/FateX#90] opened 2022-02-03 22:19 UTC
**Describe the bug**
Actor sheets will not open in current FateX on current FoundryVTT. Attempts to revert to the prior version of FateX result in working Actor sheets, but no map functionality.

**To Reproduce**
attempt to open character sheet.

**Expected behavior**
I expect the character sheet to open.

**Desktop (please complete the following information):**
Firefox

**Comment by PatrickBauer** [comment] 2022-02-04 08:28
Hey @glennfrog191,
could you specify which version of Foundry you're using right now? As well as the version of the installed FateX version? Right now I'm not able to reproduce this.

Greetings
Patrick

**Comment by PatrickBauer** [comment] 2022-02-04 13:44
Problem was caused by an external problem, closing this issue.

**Closed by PatrickBauer** 2022-02-04 13:44 UTC
Labels: bug
